---
abstract: 'Create a bot from a config file.'
author:
  - 'Mike Francis <ungrim97@gmail.com>'
build_requires:
  Test::Modern: '0.002'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v0.12.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bot-BasicBot-Pluggable-FromConfig
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Bot::BasicBot::Pluggable::FromConfig:
    file: lib/Bot/BasicBot/Pluggable/FromConfig.pm
    version: '0.5'
requires:
  Bot::BasicBot::Pluggable: '0.98'
  Carp: '1.32'
  Config::JFDI: '0.065'
  Data::Dumper: '2.151'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/ungrim97/Bot-BasicBot-Pluggable-FromConfig/issues
  homepage: https://github.com/ungrim97/Bot-BasicBot-Pluggable-FromConfig
  repository: git://github.com/ungrim97/Bot-BasicBot-Pluggable-FromConfig.git
version: '0.5'
